name: release

on:
  push:
    tags:
      - v*

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      - 
        uses: docker/setup-buildx-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn run build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - 
        name: Set env
        id: env
        run: |
          echo "::set-output name=PATCH::${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=MINOR::${PATCH%.*}"
          echo "::set-output name=MAJOR::${MINOR%.*}"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sourcegraph/lsif-node:${{ steps.env.outputs.PATCH }}
            sourcegraph/lsif-node:${{ steps.env.outputs.MINOR }}
            sourcegraph/lsif-node:${{ steps.env.outputs.MAJOR }}

